[egeria-resource-connector] Initial commit
odpi/egeria-database-connectors pull request #176
Opened 2022-07-18 10:29 UTC by lcpopa

Signed-off-by: Liviu Popa <liviu-constantin.popa@ing.com>

2022-07-19 13:36 UTC, lpalashevski requested changes
Most of the code looks good however I have one design aspect that I think should be improved: 
The jdbc connection lifecycle should be managed via the OCF methods start/disconnect and from what I can see now it is only done by the public methods open/close introduced by the JdbcMetadata interface. For me it is confusing that the connection management interface os coming from the metadata subcomponent (JdbcMetadata). I propose to move this logic in the implementation of OCF start/disconnect and keep the rest of the implementation as is.

Additional argument: In future we will expand this connector with functions to also read/write data (extended use-cases) then the purpose of the connector also extends beyond metadata and jdbc connection can be also opened for manipulating data.

Do explain if the intention was different and I am misunderstanding this part :)

2022-07-21 09:19 UTC, lcpopa commented
Start and disconnect methods are not fit for such use, since their execution does not take place before and after the execution of method refresh, respectively.

2022-07-21 11:30 UTC, lpalashevski approved these changes

2022-07-21 11:37 UTC, lpalashevski approved these changes

2022-07-22 08:39 UTC, merged