Added asset connection setup
odpi/egeria-database-connectors pull request #185
Opened 2022-07-28 18:11 UTC by lcpopa

Signed-off-by: Liviu Popa <liviu-constantin.popa@ing.com>

2022-08-10 11:09 UTC, planetf1 requested changes

2022-08-10 11:09 UTC, planetf1 commented on egeria-connector-jdbc/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/DatabaseConnectionConsumer.java
> +package org.odpi.openmetadata.adapters.connectors.integration.jdbc.transfer;
Add SPDX headers

2022-08-10 11:09 UTC, planetf1 commented on egeria-connector-jdbc/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/ffdc/JdbcConnectorAuditCode.java
> +            "An sql exception was received by method {0}. Exception message is: {1}",
usually sql is capitalised ie SQL

2022-08-10 11:09 UTC, planetf1 commented on egeria-connector-jdbc/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/DatabaseConnectionConsumer.java
> +    @Override
public methods should supply javadoc

2022-08-10 11:09 UTC, planetf1 commented on egeria-connector-jdbc/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/JdbcMetadataTransfer.java
> +            createAssetConnection(databaseElement);
public methods should have javadoc

2022-08-10 11:09 UTC, planetf1 commented on egeria-connector-jdbc/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/DatabaseConnectionConsumer.java
> +    @Override
(applies to other files also)

2022-08-11 07:57 UTC, lcpopa commented on egeria-connector-jdbc/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/DatabaseConnectionConsumer.java
> +    @Override
Javadoc will soon follow

2022-08-11 07:57 UTC, lcpopa commented on egeria-connector-jdbc/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/jdbc/transfer/JdbcMetadataTransfer.java
> +            createAssetConnection(databaseElement);
Javadoc will soon follow

2022-08-16 07:56 UTC, merged